# Generated by Django 6.0.7 on 2026-07-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('stu_class', models.CharField(max_length=500)),
                ('roll_no', models.IntegerField(unique=True)),
            ],
        ),
    ]
